export const __UNSAFE_REFERENCE_ORIGINAL_IFRAME_EVENT_KEY = `__UNSAFE_REFERENCE_ORIGINAL_IFRAME_EVENT`
export const OBOKU_READER_NAMESPACE = `@oboku/reader`
export const VIEWPORT_ADJUSTMENT_THROTTLE = 0
export const PAGINATION_UPDATE_AFTER_VIEWPORT_ADJUSTMENT_DEBOUNCE = 200