export type { Manifest } from "@prose-reader/shared"

import { createReaderWithEnhancers as createReader } from "./createReaderWithEnhancer"

export type { Theme } from "./enhancers/theme"
export { HookManager } from "./hooks/HookManager"
export { SettingsManager } from "./settings/SettingsManager"
export { DocumentRenderer } from "./spineItem/renderer/DocumentRenderer"
export { ResourceHandler } from "./spineItem/resources/ResourceHandler"

export type CreateReaderOptions = Parameters<typeof createReader>[0]

export { createReader }
export type Reader = ReturnType<typeof createReader>

export * from "./cfi"
export * from "./constants"
export * from "./context/Context"
// Exports required so that libraries can build when having reference to internal types (TS2742)
export type { EnhancerFontsInputSettings } from "./enhancers/fonts"
export * from "./enhancers/html/enhancer"
export * from "./enhancers/layout/layoutEnhancer"
export type { EnhancerLayoutInputSettings } from "./enhancers/layout/types"
export * from "./enhancers/navigation/types"
export * from "./enhancers/pagination"
export * from "./enhancers/types/enhancer"
export * from "./enhancers/zoom/types"
export * from "./features/Features"
export * from "./hooks"
export * from "./navigation/controllers/ControlledNavigationController"
export * from "./navigation/controllers/ScrollNavigationController"
export * from "./navigation/InternalNavigator"
export * from "./navigation/Locker"
export * from "./navigation/types"
export * from "./pagination"
export * from "./settings/SettingsInterface"
export * from "./settings/types"
export * from "./spine/Pages"
export * from "./spine/Spine"
export * from "./spine/SpineItemsManager"
export * from "./spine/SpineItemsObserver"
export * from "./spine/types"
export * from "./spineItem/SpineItem"
export { SpineItem } from "./spineItem/SpineItem"
export * from "./spineItem/types"
export * from "./utils/DestroyableClass"
export { isHtmlElement, isHtmlTagElement } from "./utils/dom"
export * from "./utils/frames"
export * from "./utils/objects"
export * from "./utils/ReactiveEntity"
export * from "./utils/rxjs"
export * from "./viewport/Viewport"
