name: check_publish_lib

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
  
      - uses: actions/cache@v4
        id: nx-cache
        with:
          path: |
            .nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Prepare
        run: |
          npm ci
          npx lerna run build --stream --scope @prose-reader/*

  lint:
    uses: ./.github/workflows/_lint.yml

  ts:
    uses: ./.github/workflows/_ts.yml

  tests:
    uses: ./.github/workflows/_test.yml

  publish:
    needs: [lint, ts, tests, build]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v4
        id: nx-cache
        with:
          path: |
            .nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Prepare
        run: |
          npm ci
          npx lerna run build --stream --scope @prose-reader/*

      - name: Publish
        run: |
          git config --global user.email "bret.maxime@gmail.com"
          git config --global user.name "Maxime Bret"
          npx lerna publish minor --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
